package com.mygubbi.game.dashboard.view.Catalog;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.*;
import com.vaadin.ui.Button;


public class UploadContentComposite extends CustomComponent {

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private VerticalLayout mainLayout;
	@AutoGenerated
	private Panel panel_1;
	@AutoGenerated
	private VerticalLayout verticalLayout_2;
	@AutoGenerated
	private Label label_1;
	@AutoGenerated
	private Upload upload_1;
	@AutoGenerated
	private Button button_1;
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public UploadContentComposite() {
		buildMainLayout();
		setCompositionRoot(mainLayout);

		// TODO add user code here
	}

	public Upload getUpload_1() {
		return upload_1;
	}

	public Button getButton_1() {
		return button_1;
	}

	public void setButton_1(Button button_1) {
		this.button_1 = button_1;
	}



	public VerticalLayout getVerticalLayout_2() {
		return verticalLayout_2;
	}

	public void setVerticalLayout_2(VerticalLayout verticalLayout_2) {
		this.verticalLayout_2 = verticalLayout_2;
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate(false);
		mainLayout.setWidth("100%");
		mainLayout.setHeight("100%");
		mainLayout.setMargin(false);

		// top-level component properties
		setWidth("100.0%");
		setHeight("100.0%");
		
		// panel_1
		panel_1 = buildPanel_1();
		mainLayout.addComponent(panel_1);
		
		return mainLayout;
	}

	@AutoGenerated
	private Panel buildPanel_1() {
		// common part: create layout
		panel_1 = new Panel();
		panel_1.setCaption("Upload Excel");
		panel_1.setImmediate(false);
		panel_1.setWidth("100.0%");
		panel_1.setHeight("100.0%");
				// verticalLayout_2
		verticalLayout_2 = buildVerticalLayout_2();
/*
		verticalLayout_2.addComponent(new Menu());
*/
		panel_1.setContent(verticalLayout_2);
		
		return panel_1;
	}

	@AutoGenerated
	private VerticalLayout buildVerticalLayout_2() {
		// common part: create layout
		verticalLayout_2 = new VerticalLayout();
		verticalLayout_2.setImmediate(false);
		verticalLayout_2.setWidth("100.0%");
		verticalLayout_2.setHeight("100.0%");
		verticalLayout_2.setMargin(false);
		
		// upload_1
		upload_1 = new Upload();
		upload_1.setCaption("Upload File");
		upload_1.setImmediate(false);
		upload_1.setWidth("-1px");
		upload_1.setHeight("-1px");
		verticalLayout_2.addComponent(upload_1);
		verticalLayout_2.setComponentAlignment(upload_1, new Alignment(48));
		
		// label_1
		/*label_1 = new Label();
		label_1.setCaption("Upload only xls file");
		label_1.setImmediate(false);
		label_1.setWidth("-1px");
		label_1.setHeight("-1px");
		label_1.setValue("Label");
		verticalLayout_2.addComponent(label_1);
		verticalLayout_2.setComponentAlignment(label_1, new Alignment(48));
*/
		// button_1
		/*button_1 = new Button();
		button_1.setCaption("Button");
		button_1.setImmediate(false);
		button_1.setWidth("-1px");
		button_1.setHeight("-1px");
		verticalLayout_2.addComponent(button_1);
		verticalLayout_2.setComponentAlignment(button_1, new Alignment(48));*/

		return verticalLayout_2;
	}

	/*public void setUpload_1(Upload upload_1) {
		this.upload_1 = upload_1;
	}*/

}
